"""Generate the Demand Forecasting Jupyter Notebook.

Produces notebooks/05_demand_forecasting.ipynb, a fully runnable notebook
that implements demand forecasting based on the conclusions of the
implementation plan (Phases 1-10).

Pattern follows scripts/generate_eda_dwh_assets.py.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = ROOT / "notebooks"


def main() -> None:
    NOTEBOOK_DIR.mkdir(exist_ok=True)
    cells: list[dict] = []

    def md(text: str) -> None:
        cells.append({"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)})

    def code(text: str) -> None:
        cells.append({"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": text.splitlines(keepends=True)})

    # ── 1. INTRODUCTION ──────────────────────────────────────────────────
    md(
        "# Demand Forecasting — Fashion Store Analytics\n"
        "\n"
        "## 1. Giới thiệu bài toán\n"
        "\n"
        "### Mục tiêu\n"
        "Dự báo **số lượng sản phẩm bán ra** (`daily_quantity`) trong **7 ngày tiếp theo** để hỗ trợ:\n"
        "- Lập kế hoạch tồn kho (inventory planning)\n"
        "- Phân bổ hàng hóa theo quốc gia\n"
        "- Ra quyết định chiến dịch marketing\n"
        "\n"
        "### Business Problem\n"
        "Cửa hàng thời trang Tiva bán hàng qua 2 kênh (E-commerce, App Mobile) tại 6 quốc gia châu Âu. "
        "Doanh nghiệp cần dự báo demand để giảm rủi ro hết hàng hoặc tồn kho quá mức.\n"
        "\n"
        "### Target & Horizon\n"
        "- **Target**: `daily_quantity` = SUM(quantity) theo ngày\n"
        "- **Horizon**: 7 ngày\n"
        "\n"
        "### Granularity (2 tầng)\n"
        "| Tầng | Granularity | Số series | Data points/series |\n"
        "|---|---|---|---|\n"
        "| Primary | **Category** | 5 | 51 |\n"
        "| Secondary | **Category × Country** | 30 | 20–47 |\n"
        "\n"
        "**Không** forecast theo SKU (trung bình 4.3 điểm/sản phẩm — quá sparse).\n"
        "\n"
        "### Models\n"
        "- Baseline: Naive Forecast, Moving Average (MA-7), Linear Regression\n"
        "- ML chính: **LightGBM**, XGBoost (so sánh)\n"
        "- Không dùng SARIMA/Prophet (chưa đủ seasonal cycles) và Deep Learning (quá ít data)\n"
    )

    # ── 2. IMPORTS ────────────────────────────────────────────────────────
    md(
        "## 2. Import thư viện\n"
        "\n"
        "Chỉ import những gì cần dùng, có chú thích vai trò."
    )

    code(
        "import os\n"
        "import warnings\n"
        "\n"
        "import numpy as np                          # tính toán số\n"
        "import pandas as pd                         # xử lý DataFrame\n"
        "import matplotlib.pyplot as plt              # biểu đồ cơ bản\n"
        "import seaborn as sns                        # biểu đồ đẹp hơn\n"
        "from sqlalchemy import create_engine, text   # kết nối PostgreSQL\n"
        "\n"
        "from sklearn.linear_model import LinearRegression   # baseline model\n"
        "from sklearn.metrics import mean_absolute_error, mean_squared_error\n"
        "\n"
        "import lightgbm as lgb                      # ML model chính\n"
        "import xgboost as xgb                       # ML model so sánh\n"
        "\n"
        "warnings.filterwarnings('ignore')\n"
        "sns.set_theme(style='whitegrid', font_scale=1.1)\n"
        "pd.set_option('display.max_columns', 50)\n"
        "pd.set_option('display.float_format', '{:.2f}'.format)\n"
        "\n"
        "print('All libraries imported successfully.')"
    )

    # ── 3. DATA CONNECTION ────────────────────────────────────────────────
    md(
        "## 3. Đọc dữ liệu\n"
        "\n"
        "Kết nối tới PostgreSQL, tạo mart view `mart.daily_demand` (nếu chưa tồn tại), "
        "sau đó đọc dữ liệu đã aggregate.\n"
        "\n"
        "**Nguồn dữ liệu**: `dwh.fact_sales` JOIN với `dim_date`, `dim_product`, "
        "`dim_geography`, `dim_channel` → aggregate thành daily quantity theo "
        "category × country × channel."
    )

    code(
        "from pathlib import Path\n"
        "\n"
        "# ── Xác định thư mục project ──\n"
        "NOTEBOOK_DIR = Path.cwd()\n"
        "if not (NOTEBOOK_DIR / 'data' / 'raw').exists():\n"
        "    NOTEBOOK_DIR = NOTEBOOK_DIR.parent\n"
        "RAW_DIR = NOTEBOOK_DIR / 'data' / 'raw'\n"
        "\n"
        "# ── Chiến lược: PostgreSQL > CSV fallback ──\n"
        "USE_DB = False\n"
        "\n"
        "try:\n"
        "    url = os.getenv(\n"
        '        "DATABASE_URL",\n'
        '        "postgresql+psycopg2://postgres:postgres@localhost:5432/fashion_dw"\n'
        "    )\n"
        "    engine = create_engine(url)\n"
        "    with engine.connect() as conn:\n"
        '        conn.execute(text("SELECT 1"))\n'
        "    USE_DB = True\n"
        '    print("PostgreSQL connected.")\n'
        "except Exception:\n"
        '    print("PostgreSQL not available — using CSV fallback.")\n'
        "\n"
        "\n"
        "if USE_DB:\n"
        "    # Tạo mart view và đọc từ DB\n"
        "    MART_SQL = \"\"\"\n"
        "    CREATE OR REPLACE VIEW mart.daily_demand AS\n"
        "    SELECT\n"
        "        d.full_date, d.day_of_week, d.day_name, d.is_weekend,\n"
        "        d.week_of_year, d.month_number, d.quarter_number, d.year_number,\n"
        "        p.category, g.country, ch.channel_name,\n"
        "        SUM(fs.quantity) AS daily_quantity,\n"
        "        SUM(fs.net_amount) AS daily_revenue,\n"
        "        SUM(fs.discount_amount) AS daily_discount_amount,\n"
        "        COUNT(DISTINCT fs.sale_id) AS daily_orders,\n"
        "        COUNT(fs.sales_key) AS daily_line_items,\n"
        "        AVG(fs.discount_percent) AS avg_discount_percent,\n"
        "        MAX(CASE WHEN fs.is_discounted THEN 1 ELSE 0 END) AS has_discount,\n"
        "        MAX(CASE WHEN fs.campaign_key IS NOT NULL THEN 1 ELSE 0 END) AS has_campaign\n"
        "    FROM dwh.fact_sales fs\n"
        "    JOIN dwh.dim_date d ON fs.sale_date_key = d.date_key\n"
        "    JOIN dwh.dim_product p ON fs.product_key = p.product_key\n"
        "    JOIN dwh.dim_geography g ON fs.geography_key = g.geography_key\n"
        "    JOIN dwh.dim_channel ch ON fs.channel_key = ch.channel_key\n"
        "    GROUP BY d.full_date, d.day_of_week, d.day_name, d.is_weekend,\n"
        "             d.week_of_year, d.month_number, d.quarter_number, d.year_number,\n"
        "             p.category, g.country, ch.channel_name\n"
        "    \"\"\"\n"
        "    with engine.begin() as conn:\n"
        '        conn.execute(text("CREATE SCHEMA IF NOT EXISTS mart"))\n'
        "        conn.execute(text(MART_SQL))\n"
        "    df_raw = pd.read_sql(\n"
        '        "SELECT * FROM mart.daily_demand ORDER BY full_date, category, country",\n'
        "        engine,\n"
        "    )\n"
        '    df_raw["full_date"] = pd.to_datetime(df_raw["full_date"])\n'
        '    print(f"Loaded {len(df_raw):,} rows from mart.daily_demand (PostgreSQL)")\n'
        "\n"
        "else:\n"
        "    # ── CSV Fallback: tái tạo logic mart view bằng pandas ──\n"
        "    # Đọc raw CSV\n"
        '    sales = pd.read_csv(RAW_DIR / "dataset_fashion_store_sales.csv")\n'
        '    items = pd.read_csv(RAW_DIR / "dataset_fashion_store_salesitems.csv")\n'
        '    products = pd.read_csv(RAW_DIR / "dataset_fashion_store_products.csv")\n'
        '    campaigns = pd.read_csv(RAW_DIR / "dataset_fashion_store_campaigns.csv")\n'
        "\n"
        "    # Parse types\n"
        '    items["sale_date"] = pd.to_datetime(items["sale_date"])\n'
        "    for col in ['quantity', 'original_price', 'unit_price', 'item_total',\n"
        "                'discount_applied']:\n"
        "        items[col] = pd.to_numeric(items[col], errors='coerce')\n"
        '    items["discount_percent_num"] = (\n'
        '        pd.to_numeric(items["discount_percent"].astype(str)\n'
        "                      .str.replace('%', '', regex=False).str.strip(),\n"
        "                      errors='coerce') / 100\n"
        "    )\n"
        "\n"
        "    # Join items + products + sales để lấy category, country, channel\n"
        '    merged = items.merge(products[["product_id", "category"]], on="product_id", how="left")\n'
        '    merged = merged.merge(sales[["sale_id", "country"]], on="sale_id", how="left")\n'
        "\n"
        "    # Tính net_amount, discount_amount\n"
        '    merged["net_amount"] = merged["item_total"]\n'
        '    merged["gross_amount"] = merged["quantity"] * merged["original_price"]\n'
        '    merged["discount_amount"] = merged["gross_amount"] - merged["net_amount"]\n'
        '    merged["is_discounted"] = merged["discounted"].astype(int)\n'
        "\n"
        "    # Campaign mapping: kiểm tra sale_date nằm trong khoảng campaign\n"
        '    campaigns["start_date"] = pd.to_datetime(campaigns["start_date"])\n'
        '    campaigns["end_date"] = pd.to_datetime(campaigns["end_date"])\n'
        '    merged["has_campaign_flag"] = 0\n'
        "    for _, camp in campaigns.iterrows():\n"
        '        mask = (merged["sale_date"] >= camp["start_date"]) & (merged["sale_date"] <= camp["end_date"])\n'
        '        merged.loc[mask, "has_campaign_flag"] = 1\n'
        "\n"
        "    # Date features\n"
        '    merged["day_of_week"] = merged["sale_date"].dt.isocalendar().day.astype(int)\n'
        '    merged["day_name"] = merged["sale_date"].dt.day_name()\n'
        '    merged["is_weekend"] = merged["day_of_week"].isin([6, 7])\n'
        '    merged["week_of_year"] = merged["sale_date"].dt.isocalendar().week.astype(int)\n'
        '    merged["month_number"] = merged["sale_date"].dt.month\n'
        '    merged["quarter_number"] = merged["sale_date"].dt.quarter\n'
        '    merged["year_number"] = merged["sale_date"].dt.year\n'
        "\n"
        "    # Aggregate giống mart.daily_demand\n"
        "    df_raw = (\n"
        "        merged\n"
        '        .groupby(["sale_date", "day_of_week", "day_name", "is_weekend",\n'
        '                  "week_of_year", "month_number", "quarter_number", "year_number",\n'
        '                  "category", "country", "channel"], as_index=False)\n'
        "        .agg(\n"
        "            daily_quantity=('quantity', 'sum'),\n"
        "            daily_revenue=('net_amount', 'sum'),\n"
        "            daily_discount_amount=('discount_amount', 'sum'),\n"
        "            daily_orders=('sale_id', 'nunique'),\n"
        "            daily_line_items=('item_id', 'count'),\n"
        "            avg_discount_percent=('discount_percent_num', 'mean'),\n"
        "            has_discount=('is_discounted', 'max'),\n"
        "            has_campaign=('has_campaign_flag', 'max'),\n"
        "        )\n"
        "    )\n"
        '    df_raw = df_raw.rename(columns={"sale_date": "full_date", "channel": "channel_name"})\n'
        '    df_raw = df_raw.sort_values(["full_date", "category", "country"]).reset_index(drop=True)\n'
        '    print(f"Loaded {len(df_raw):,} rows via CSV fallback (equivalent to mart.daily_demand)")\n'
        "\n"
        'print(f"Date range: {df_raw[\"full_date\"].min().date()} → {df_raw[\"full_date\"].max().date()}")\n'
        'print(f"Categories: {sorted(df_raw[\"category\"].unique())}")\n'
        'print(f"Countries: {sorted(df_raw[\"country\"].unique())}")'
    )


    # ── 4. DATA EXPLORATION ───────────────────────────────────────────────
    md(
        "## 4. Khảo sát dữ liệu\n"
        "\n"
        "Kiểm tra shape, dtypes, missing values, thống kê mô tả."
    )

    code(
        "print('Shape:', df_raw.shape)\n"
        "print()\n"
        "print('--- Dtypes ---')\n"
        "print(df_raw.dtypes)\n"
        "print()\n"
        "print('--- Missing Values ---')\n"
        "print(df_raw.isnull().sum())\n"
        "print()\n"
        "print('--- Date Range ---')\n"
        "print(f'From: {df_raw[\"full_date\"].min()}')\n"
        "print(f'To:   {df_raw[\"full_date\"].max()}')\n"
        "print(f'Unique dates: {df_raw[\"full_date\"].nunique()}')\n"
        "print()\n"
        "print('--- Categories ---')\n"
        "print(df_raw['category'].value_counts())\n"
        "print()\n"
        "print('--- Countries ---')\n"
        "print(df_raw['country'].value_counts())\n"
        "print()\n"
        "print('--- Channels ---')\n"
        "print(df_raw['channel_name'].value_counts())"
    )

    code(
        "# Thống kê mô tả các cột số\n"
        "df_raw[['daily_quantity', 'daily_revenue', 'daily_discount_amount',\n"
        "        'daily_orders', 'has_discount', 'has_campaign']].describe()"
    )

    # ── 5. PREPARE FORECASTING DATA ──────────────────────────────────────
    md(
        "## 5. Chuẩn bị dữ liệu forecasting\n"
        "\n"
        "### Bước 1: Aggregate\n"
        "Mart view đã aggregate theo date × category × country × channel. "
        "Bây giờ ta cần aggregate thêm:\n"
        "- **Category level**: gộp tất cả country và channel → 1 daily_quantity per category per date\n"
        "- **Category × Country level**: gộp channel → 1 daily_quantity per category × country per date\n"
        "\n"
        "### Bước 2: Fill missing dates\n"
        "Không phải ngày nào cũng có giao dịch cho mọi category/country. "
        "Các ngày thiếu sẽ được fill `daily_quantity = 0` (không bán = 0 sản phẩm)."
    )

    code(
        "# ── Category level: gộp tất cả country/channel ──\n"
        "cat_agg = (\n"
        "    df_raw\n"
        "    .groupby(['full_date', 'category'], as_index=False)\n"
        "    .agg(\n"
        "        daily_quantity=('daily_quantity', 'sum'),\n"
        "        daily_revenue=('daily_revenue', 'sum'),\n"
        "        has_discount=('has_discount', 'max'),\n"
        "        has_campaign=('has_campaign', 'max'),\n"
        "    )\n"
        ")\n"
        "\n"
        "# Fill missing dates: mỗi category phải có đủ 51 ngày\n"
        "all_dates = pd.date_range(\n"
        "    cat_agg['full_date'].min(), cat_agg['full_date'].max(), freq='D'\n"
        ")\n"
        "all_categories = sorted(cat_agg['category'].unique())\n"
        "full_idx = pd.MultiIndex.from_product(\n"
        "    [all_dates, all_categories], names=['full_date', 'category']\n"
        ")\n"
        "cat_daily = (\n"
        "    cat_agg\n"
        "    .set_index(['full_date', 'category'])\n"
        "    .reindex(full_idx, fill_value=0)\n"
        "    .reset_index()\n"
        ")\n"
        "\n"
        "print(f'Category-level dataset: {cat_daily.shape}')\n"
        "print(f'Categories: {all_categories}')\n"
        "print(f'Date range: {cat_daily[\"full_date\"].min()} → {cat_daily[\"full_date\"].max()}')\n"
        "print(f'Days per category: {cat_daily.groupby(\"category\").size().unique()}')"
    )

    code(
        "# ── Category × Country level ──\n"
        "catco_agg = (\n"
        "    df_raw\n"
        "    .groupby(['full_date', 'category', 'country'], as_index=False)\n"
        "    .agg(\n"
        "        daily_quantity=('daily_quantity', 'sum'),\n"
        "        daily_revenue=('daily_revenue', 'sum'),\n"
        "        has_discount=('has_discount', 'max'),\n"
        "        has_campaign=('has_campaign', 'max'),\n"
        "    )\n"
        ")\n"
        "\n"
        "all_countries = sorted(df_raw['country'].unique())\n"
        "full_idx_cc = pd.MultiIndex.from_product(\n"
        "    [all_dates, all_categories, all_countries],\n"
        "    names=['full_date', 'category', 'country'],\n"
        ")\n"
        "catco_daily = (\n"
        "    catco_agg\n"
        "    .set_index(['full_date', 'category', 'country'])\n"
        "    .reindex(full_idx_cc, fill_value=0)\n"
        "    .reset_index()\n"
        ")\n"
        "\n"
        "print(f'Category×Country dataset: {catco_daily.shape}')\n"
        "print(f'Countries: {all_countries}')\n"
        "print(f'Series count: {catco_daily.groupby([\"category\", \"country\"]).ngroups}')\n"
        "print(f'Data points per series:')\n"
        "print(catco_daily.groupby(['category', 'country']).size().describe())"
    )

    # ── 6. EDA TIME SERIES ────────────────────────────────────────────────
    md(
        "## 6. EDA cho Time Series\n"
        "\n"
        "Phân tích xu hướng, phân phối, và mối quan hệ giữa các biến.\n"
        "\n"
        "> **Lưu ý**: Dữ liệu chỉ có 51 ngày (2025-04-04 → 2025-06-17). "
        "Không đủ để phát hiện seasonal patterns dài hạn (cần ≥ 2 năm). "
        "EDA ở đây tập trung vào **trend ngắn hạn** và **weekly patterns**."
    )

    code(
        "# ── Tổng daily_quantity toàn hệ thống theo thời gian ──\n"
        "total_daily = cat_daily.groupby('full_date')['daily_quantity'].sum().reset_index()\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(14, 4))\n"
        "ax.plot(total_daily['full_date'], total_daily['daily_quantity'],\n"
        "        marker='.', linewidth=1.5, color='#2196F3')\n"
        "ax.set_title('Tổng daily_quantity toàn hệ thống', fontsize=14, fontweight='bold')\n"
        "ax.set_xlabel('Date')\n"
        "ax.set_ylabel('Quantity')\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: Quantity dao động quanh 80–200 đơn vị/ngày. '\n"
        "      'Có thể thấy biến động tuần (ngày cuối tuần giảm hoặc tăng). '\n"
        "      'Chưa đủ dữ liệu để kết luận trend dài hạn.')"
    )

    code(
        "# ── Daily quantity theo Category ──\n"
        "fig, ax = plt.subplots(figsize=(14, 5))\n"
        "for cat in all_categories:\n"
        "    mask = cat_daily['category'] == cat\n"
        "    ax.plot(cat_daily.loc[mask, 'full_date'],\n"
        "            cat_daily.loc[mask, 'daily_quantity'],\n"
        "            marker='.', linewidth=1, alpha=0.8, label=cat)\n"
        "ax.set_title('Daily Quantity theo Category', fontsize=14, fontweight='bold')\n"
        "ax.set_xlabel('Date')\n"
        "ax.set_ylabel('Quantity')\n"
        "ax.legend(loc='upper right')\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: Các category có pattern tương tự nhau (cùng tăng/giảm). '\n"
        "      'Shoes và Dresses có xu hướng quantity cao hơn.')"
    )

    code(
        "# ── Phân phối daily_quantity theo Category ──\n"
        "fig, axes = plt.subplots(1, 5, figsize=(18, 4), sharey=True)\n"
        "for i, cat in enumerate(all_categories):\n"
        "    data = cat_daily.loc[cat_daily['category'] == cat, 'daily_quantity']\n"
        "    axes[i].hist(data, bins=15, color='#4CAF50', edgecolor='white', alpha=0.8)\n"
        "    axes[i].set_title(cat, fontsize=11)\n"
        "    axes[i].set_xlabel('Quantity')\n"
        "    if i == 0:\n"
        "        axes[i].set_ylabel('Frequency')\n"
        "fig.suptitle('Phân phối Daily Quantity theo Category', fontsize=14, fontweight='bold', y=1.02)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: Phân phối gần normal, phù hợp cho regression models.')"
    )

    code(
        "# ── Heatmap: Trung bình quantity theo Day of Week × Category ──\n"
        "cat_daily_copy = cat_daily.copy()\n"
        "cat_daily_copy['day_of_week'] = cat_daily_copy['full_date'].dt.day_name()\n"
        "pivot = cat_daily_copy.groupby(['day_of_week', 'category'])['daily_quantity'].mean().unstack()\n"
        "# Sắp xếp theo thứ tự ngày trong tuần\n"
        "day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']\n"
        "pivot = pivot.reindex(day_order)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "sns.heatmap(pivot, annot=True, fmt='.1f', cmap='YlOrRd', ax=ax)\n"
        "ax.set_title('Trung bình Daily Quantity: Day of Week × Category', fontsize=13, fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: Biến động theo ngày trong tuần có thể là feature quan trọng.')"
    )

    code(
        "# ── Tổng quantity theo Country ──\n"
        "country_qty = catco_daily.groupby('country')['daily_quantity'].sum().sort_values(ascending=True)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 4))\n"
        "country_qty.plot(kind='barh', ax=ax, color='#FF9800', edgecolor='white')\n"
        "ax.set_title('Tổng Quantity theo Country', fontsize=13, fontweight='bold')\n"
        "ax.set_xlabel('Total Quantity')\n"
        "for i, v in enumerate(country_qty.values):\n"
        "    ax.text(v + 10, i, f'{v:,.0f}', va='center', fontsize=10)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: France, Germany dẫn đầu. Portugal có demand thấp nhất.')"
    )

    code(
        "# ── Tỷ lệ discount và campaign ──\n"
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
        "\n"
        "disc_rate = cat_daily.groupby('full_date')['has_discount'].max()\n"
        "axes[0].bar(disc_rate.index, disc_rate.values, color='#E91E63', alpha=0.6, width=1)\n"
        "axes[0].set_title('Has Discount flag theo ngày', fontsize=12)\n"
        "axes[0].set_ylabel('Flag (0/1)')\n"
        "axes[0].tick_params(axis='x', rotation=45)\n"
        "\n"
        "camp_rate = cat_daily.groupby('full_date')['has_campaign'].max()\n"
        "axes[1].bar(camp_rate.index, camp_rate.values, color='#9C27B0', alpha=0.6, width=1)\n"
        "axes[1].set_title('Has Campaign flag theo ngày', fontsize=12)\n"
        "axes[1].set_ylabel('Flag (0/1)')\n"
        "axes[1].tick_params(axis='x', rotation=45)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Nhận xét: Discount và campaign không xảy ra mọi ngày — '\n"
        "      'có thể giúp model phân biệt ngày có/không khuyến mãi.')"
    )

    # ── 7. FEATURE ENGINEERING ────────────────────────────────────────────
    md(
        "## 7. Feature Engineering\n"
        "\n"
        "Tạo features phục vụ forecasting. Tất cả features được sinh trong Python, "
        "**không** đẩy vào DWH.\n"
        "\n"
        "### Nguyên tắc tránh Data Leakage\n"
        "- **Lag features**: `shift(n)` — chỉ dùng giá trị quá khứ\n"
        "- **Rolling features**: tính trên dữ liệu đã `shift(1)` — "
        "không bao gồm giá trị hiện tại\n"
        "- **Không** dùng thông tin tương lai bằng bất kỳ cách nào"
    )

    code(
        "def create_features(df, group_cols):\n"
        '    """Tạo time-series features cho demand forecasting.\n'
        "\n"
        "    Parameters\n"
        "    ----------\n"
        "    df : DataFrame cần có cột 'full_date' và 'daily_quantity'\n"
        "    group_cols : list tên cột nhóm (ví dụ ['category'] hoặc ['category', 'country'])\n"
        "\n"
        "    Returns\n"
        "    -------\n"
        '    DataFrame với features mới, đã drop NaN do lag.\n'
        '    """\n'
        "    df = df.sort_values(group_cols + ['full_date']).copy()\n"
        "\n"
        "    # ── Time features ──\n"
        "    df['day_of_week'] = df['full_date'].dt.dayofweek          # 0=Mon, 6=Sun\n"
        "    df['day_of_month'] = df['full_date'].dt.day\n"
        "    df['week_of_year'] = df['full_date'].dt.isocalendar().week.astype(int)\n"
        "    df['month'] = df['full_date'].dt.month\n"
        "    df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)\n"
        "    df['is_month_start'] = df['full_date'].dt.is_month_start.astype(int)\n"
        "    df['is_month_end'] = df['full_date'].dt.is_month_end.astype(int)\n"
        "\n"
        "    # ── Lag features (per group) ──\n"
        "    # lag_1: demand hôm qua → auto-correlation ngắn hạn\n"
        "    # lag_7: demand cùng ngày tuần trước → weekly pattern\n"
        "    for lag in [1, 7]:\n"
        "        df[f'lag_{lag}'] = df.groupby(group_cols)['daily_quantity'].shift(lag)\n"
        "\n"
        "    # ── Rolling features (shift 1 trước, rồi rolling → tránh leakage) ──\n"
        "    # rolling_mean_7: xu hướng trung bình 7 ngày gần nhất (smoothed)\n"
        "    # rolling_std_7 : độ biến động 7 ngày → demand ổn định hay biến động?\n"
        "    shifted = df.groupby(group_cols)['daily_quantity'].shift(1)\n"
        "    df['rolling_mean_7'] = (\n"
        "        shifted.groupby(df[group_cols].apply(tuple, axis=1))\n"
        "        .transform(lambda x: x.rolling(7, min_periods=1).mean())\n"
        "    )\n"
        "    df['rolling_std_7'] = (\n"
        "        shifted.groupby(df[group_cols].apply(tuple, axis=1))\n"
        "        .transform(lambda x: x.rolling(7, min_periods=1).std())\n"
        "    ).fillna(0)\n"
        "\n"
        "    # ── Promotion features ──\n"
        "    # has_discount: ngày có sản phẩm giảm giá không\n"
        "    # has_campaign: ngày có campaign marketing không\n"
        "    # (đã có sẵn trong dataset từ mart view)\n"
        "\n"
        "    # Drop rows thiếu lag features (7 ngày đầu)\n"
        "    df = df.dropna(subset=['lag_1', 'lag_7']).reset_index(drop=True)\n"
        "\n"
        "    return df\n"
        "\n"
        "\n"
        "print('Function create_features() defined.')"
    )

    code(
        "# ── Áp dụng Feature Engineering ──\n"
        "\n"
        "# Category level\n"
        "cat_features = create_features(cat_daily, group_cols=['category'])\n"
        "print(f'Category features shape: {cat_features.shape}')\n"
        "print(f'Date range after lag drop: '\n"
        "      f'{cat_features[\"full_date\"].min()} → {cat_features[\"full_date\"].max()}')\n"
        "print(f'Columns: {list(cat_features.columns)}')\n"
        "print()\n"
        "\n"
        "# Category × Country level\n"
        "catco_features = create_features(catco_daily, group_cols=['category', 'country'])\n"
        "print(f'Category×Country features shape: {catco_features.shape}')\n"
        "print(f'Date range after lag drop: '\n"
        "      f'{catco_features[\"full_date\"].min()} → {catco_features[\"full_date\"].max()}')"
    )

    code(
        "# Kiểm tra features\n"
        "cat_features.head(10)"
    )

    # ── 8. TRAIN/TEST SPLIT ───────────────────────────────────────────────
    md(
        "## 8. Chia Train/Test — Time-based Split\n"
        "\n"
        "### Vì sao KHÔNG dùng Random Split?\n"
        "- **Data leakage**: Random split cho phép model \"nhìn thấy tương lai\" → đánh giá quá lạc quan\n"
        "- **Lag features bị corrupt**: lag_1 của ngày test có thể lấy từ ngày train đã thấy\n"
        "- **Auto-correlation**: các ngày liền kề tương quan cao → random split vi phạm giả định independence\n"
        "- **Business logic**: trong thực tế ta chỉ dự báo tương lai từ quá khứ\n"
        "\n"
        "### Phương pháp: Expanding Window\n"
        "```\n"
        "Fold 1: Train [───────] Val [──]\n"
        "Fold 2: Train [──────────] Val [──]\n"
        "Fold 3: Train [─────────────] Val [──]\n"
        "Final:  Train [────────────────] Test [──]  (7 ngày cuối)\n"
        "```\n"
        "Cutoff ngày áp dụng **đồng nhất** cho tất cả series."
    )

    code(
        "# ── Thiết lập parameters ──\n"
        "HORIZON = 7        # dự báo 7 ngày\n"
        "N_CV_FOLDS = 4     # số fold cross-validation\n"
        "\n"
        "# Feature columns (chung cho cả 2 granularity)\n"
        "TIME_FEATURES = ['day_of_week', 'day_of_month', 'week_of_year', 'month',\n"
        "                 'is_weekend', 'is_month_start', 'is_month_end']\n"
        "LAG_FEATURES = ['lag_1', 'lag_7']\n"
        "ROLLING_FEATURES = ['rolling_mean_7', 'rolling_std_7']\n"
        "PROMO_FEATURES = ['has_discount', 'has_campaign']\n"
        "\n"
        "NUMERIC_FEATURES = TIME_FEATURES + LAG_FEATURES + ROLLING_FEATURES + PROMO_FEATURES\n"
        "TARGET = 'daily_quantity'\n"
        "\n"
        "print(f'Horizon: {HORIZON} ngày')\n"
        "print(f'CV Folds: {N_CV_FOLDS}')\n"
        "print(f'Numeric features ({len(NUMERIC_FEATURES)}): {NUMERIC_FEATURES}')"
    )

    code(
        "def make_time_splits(df, date_col, horizon, n_folds):\n"
        '    """Tạo expanding-window time-based CV folds + final test split.\n'
        "\n"
        "    Returns\n"
        "    -------\n"
        "    folds : list of (train_idx, val_idx)\n"
        "    test_idx : index for final hold-out test set\n"
        '    """\n'
        "    sorted_dates = sorted(df[date_col].unique())\n"
        "    n_dates = len(sorted_dates)\n"
        "\n"
        "    # Final test: last `horizon` dates\n"
        "    test_start_date = sorted_dates[-horizon]\n"
        "    test_idx = df[df[date_col] >= test_start_date].index\n"
        "\n"
        "    # CV folds: carve from the remaining dates\n"
        "    cv_dates = sorted_dates[:-horizon]\n"
        "    n_cv = len(cv_dates)\n"
        "\n"
        "    folds = []\n"
        "    for k in range(n_folds):\n"
        "        # Expanding window: each fold adds ~(n_cv - min_train) / n_folds days\n"
        "        min_train = max(14, n_cv // 3)  # at least 14 days for training\n"
        "        val_size = horizon\n"
        "        val_end_idx = min_train + (k + 1) * ((n_cv - min_train) // n_folds) + val_size - 1\n"
        "        if val_end_idx >= n_cv:\n"
        "            val_end_idx = n_cv - 1\n"
        "        val_start_idx = val_end_idx - val_size + 1\n"
        "\n"
        "        train_end_date = cv_dates[val_start_idx - 1]\n"
        "        val_start_date = cv_dates[val_start_idx]\n"
        "        val_end_date = cv_dates[min(val_end_idx, n_cv - 1)]\n"
        "\n"
        "        train_mask = df[date_col] <= train_end_date\n"
        "        val_mask = (df[date_col] >= val_start_date) & (df[date_col] <= val_end_date)\n"
        "\n"
        "        if train_mask.sum() > 0 and val_mask.sum() > 0:\n"
        "            folds.append((df[train_mask].index, df[val_mask].index))\n"
        "\n"
        "    return folds, test_idx\n"
        "\n"
        "\n"
        "# Tạo splits cho Category level\n"
        "cat_folds, cat_test_idx = make_time_splits(\n"
        "    cat_features, 'full_date', HORIZON, N_CV_FOLDS\n"
        ")\n"
        "print(f'Category level: {len(cat_folds)} CV folds')\n"
        "for i, (tr, va) in enumerate(cat_folds):\n"
        "    print(f'  Fold {i+1}: train={len(tr)} rows, val={len(va)} rows, '\n"
        "          f'train dates up to {cat_features.loc[tr, \"full_date\"].max().date()}, '\n"
        "          f'val from {cat_features.loc[va, \"full_date\"].min().date()}')\n"
        "print(f'  Test: {len(cat_test_idx)} rows '\n"
        "      f'({cat_features.loc[cat_test_idx, \"full_date\"].min().date()} → '\n"
        "      f'{cat_features.loc[cat_test_idx, \"full_date\"].max().date()})')\n"
        "\n"
        "# Tạo splits cho Category×Country level\n"
        "catco_folds, catco_test_idx = make_time_splits(\n"
        "    catco_features, 'full_date', HORIZON, N_CV_FOLDS\n"
        ")\n"
        "print(f'\\nCategory×Country level: {len(catco_folds)} CV folds')\n"
        "for i, (tr, va) in enumerate(catco_folds):\n"
        "    print(f'  Fold {i+1}: train={len(tr)} rows, val={len(va)} rows')\n"
        "print(f'  Test: {len(catco_test_idx)} rows')"
    )

    # ── 9. METRICS ────────────────────────────────────────────────────────
    md(
        "## 9. Metrics đánh giá\n"
        "\n"
        "| Metric | Công thức | Khi nào dùng |\n"
        "|---|---|---|\n"
        "| **MAE** (chính) | mean(\\|y - ŷ\\|) | Robust, dễ hiểu: sai bao nhiêu đơn vị |\n"
        "| **RMSE** | √mean((y-ŷ)²) | Phạt sai lệch lớn |\n"
        "| **SMAPE** | 200 × mean(\\|y-ŷ\\| / (\\|y\\|+\\|ŷ\\|)) | Tỷ lệ %, xử lý được y=0 |"
    )

    code(
        "def smape(y_true, y_pred):\n"
        '    """Symmetric Mean Absolute Percentage Error (0–200%)."""\n'
        "    y_true, y_pred = np.array(y_true, dtype=float), np.array(y_pred, dtype=float)\n"
        "    denom = np.abs(y_true) + np.abs(y_pred)\n"
        "    ratio = np.where(denom == 0, 0.0, np.abs(y_true - y_pred) / denom)\n"
        "    return 200.0 * np.mean(ratio)\n"
        "\n"
        "\n"
        "def evaluate(y_true, y_pred, label=''):\n"
        '    """Tính MAE, RMSE, SMAPE và trả về dict."""\n'
        "    mae = mean_absolute_error(y_true, y_pred)\n"
        "    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n"
        "    sm = smape(y_true, y_pred)\n"
        "    return {'model': label, 'MAE': mae, 'RMSE': rmse, 'SMAPE': sm}\n"
        "\n"
        "\n"
        "print('Metric functions defined: smape(), evaluate()')"
    )

    # ── 10. BASELINE MODELS ───────────────────────────────────────────────
    md(
        "## 10. Baseline Models\n"
        "\n"
        "Ba baseline đơn giản để thiết lập benchmark:\n"
        "1. **Naive Forecast**: dự báo = giá trị ngày hôm qua (`lag_1`)\n"
        "2. **Moving Average 7**: dự báo = trung bình 7 ngày gần nhất (`rolling_mean_7`)\n"
        "3. **Linear Regression**: model tuyến tính với toàn bộ numeric features"
    )

    code(
        "def run_baselines(df, feature_cols, folds, test_idx, label_prefix=''):\n"
        '    """Chạy baseline models trên CV folds và test set.\n'
        "\n"
        "    Returns\n"
        "    -------\n"
        '    results : list of dicts (mỗi dict = 1 model × 1 fold/test)\n'
        '    """\n'
        "    results = []\n"
        "\n"
        "    # --- CV Folds ---\n"
        "    for fold_i, (train_idx, val_idx) in enumerate(folds):\n"
        "        y_val = df.loc[val_idx, TARGET].values\n"
        "\n"
        "        # Naive: predict = lag_1\n"
        "        naive_pred = df.loc[val_idx, 'lag_1'].values\n"
        "        r = evaluate(y_val, naive_pred, f'{label_prefix}Naive')\n"
        "        r['fold'] = fold_i + 1\n"
        "        results.append(r)\n"
        "\n"
        "        # MA-7: predict = rolling_mean_7\n"
        "        ma7_pred = df.loc[val_idx, 'rolling_mean_7'].values\n"
        "        r = evaluate(y_val, ma7_pred, f'{label_prefix}MA-7')\n"
        "        r['fold'] = fold_i + 1\n"
        "        results.append(r)\n"
        "\n"
        "        # Linear Regression\n"
        "        X_tr = df.loc[train_idx, feature_cols].values\n"
        "        y_tr = df.loc[train_idx, TARGET].values\n"
        "        X_va = df.loc[val_idx, feature_cols].values\n"
        "        lr = LinearRegression()\n"
        "        lr.fit(X_tr, y_tr)\n"
        "        lr_pred = np.clip(lr.predict(X_va), 0, None)  # quantity >= 0\n"
        "        r = evaluate(y_val, lr_pred, f'{label_prefix}LinReg')\n"
        "        r['fold'] = fold_i + 1\n"
        "        results.append(r)\n"
        "\n"
        "    # --- Final Test ---\n"
        "    y_test = df.loc[test_idx, TARGET].values\n"
        "\n"
        "    # Naive test\n"
        "    naive_test = df.loc[test_idx, 'lag_1'].values\n"
        "    r = evaluate(y_test, naive_test, f'{label_prefix}Naive')\n"
        "    r['fold'] = 'Test'\n"
        "    results.append(r)\n"
        "\n"
        "    # MA-7 test\n"
        "    ma7_test = df.loc[test_idx, 'rolling_mean_7'].values\n"
        "    r = evaluate(y_test, ma7_test, f'{label_prefix}MA-7')\n"
        "    r['fold'] = 'Test'\n"
        "    results.append(r)\n"
        "\n"
        "    # LinReg test\n"
        "    train_all_idx = df.index.difference(test_idx)\n"
        "    lr = LinearRegression()\n"
        "    lr.fit(df.loc[train_all_idx, feature_cols], df.loc[train_all_idx, TARGET])\n"
        "    lr_test_pred = np.clip(lr.predict(df.loc[test_idx, feature_cols]), 0, None)\n"
        "    r = evaluate(y_test, lr_test_pred, f'{label_prefix}LinReg')\n"
        "    r['fold'] = 'Test'\n"
        "    results.append(r)\n"
        "\n"
        "    return results\n"
        "\n"
        "\n"
        "print('Function run_baselines() defined.')"
    )

    code(
        "# ── Chạy baselines: Category level ──\n"
        "cat_baseline_results = run_baselines(\n"
        "    cat_features, NUMERIC_FEATURES, cat_folds, cat_test_idx, label_prefix=''\n"
        ")\n"
        "cat_baseline_df = pd.DataFrame(cat_baseline_results)\n"
        "\n"
        "print('=== Category Level — Baseline Results (CV mean ± std) ===')\n"
        "cv_summary = (\n"
        "    cat_baseline_df[cat_baseline_df['fold'] != 'Test']\n"
        "    .groupby('model')[['MAE', 'RMSE', 'SMAPE']]\n"
        "    .agg(['mean', 'std'])\n"
        ")\n"
        "print(cv_summary.round(2))\n"
        "print()\n"
        "\n"
        "print('=== Category Level — Baseline Results (Final Test) ===')\n"
        "print(cat_baseline_df[cat_baseline_df['fold'] == 'Test'][['model', 'MAE', 'RMSE', 'SMAPE']].to_string(index=False))"
    )

    # ── 11. ML MODELS ─────────────────────────────────────────────────────
    md(
        "## 11. ML Models\n"
        "\n"
        "### LightGBM (Model chính)\n"
        "- Xử lý categorical features native\n"
        "- Nhanh, ít overfit với dataset nhỏ\n"
        "- Feature importance built-in\n"
        "\n"
        "### XGBoost (So sánh)\n"
        "- Robust, accuracy cao\n"
        "- So sánh để chọn model tốt nhất\n"
        "\n"
        "Cả hai đều được train với **global model** — 1 model cho tất cả series, "
        "với category/country là features."
    )

    code(
        "def encode_categoricals(df, cat_cols):\n"
        '    """Label-encode categorical columns. Returns df copy + mapping."""\n'
        "    df = df.copy()\n"
        "    mappings = {}\n"
        "    for col in cat_cols:\n"
        "        df[col + '_enc'] = df[col].astype('category').cat.codes\n"
        "        mappings[col] = dict(enumerate(df[col].astype('category').cat.categories))\n"
        "    return df, mappings\n"
        "\n"
        "\n"
        "def run_ml_models(df, feature_cols, cat_feature_cols, folds, test_idx, label_prefix=''):\n"
        '    """Train LightGBM + XGBoost trên CV folds và test set.\n'
        "\n"
        "    Returns\n"
        "    -------\n"
        '    results, lgb_model, xgb_model, test_preds\n'
        '    """\n'
        "    results = []\n"
        "    lgb_model_final = None\n"
        "    xgb_model_final = None\n"
        "    test_preds = {}\n"
        "\n"
        "    # LightGBM params\n"
        "    lgb_params = {\n"
        "        'objective': 'regression',\n"
        "        'metric': 'mae',\n"
        "        'verbosity': -1,\n"
        "        'num_leaves': 31,\n"
        "        'learning_rate': 0.05,\n"
        "        'n_estimators': 200,\n"
        "        'min_child_samples': 5,\n"
        "        'subsample': 0.8,\n"
        "        'colsample_bytree': 0.8,\n"
        "        'random_state': 42,\n"
        "        'n_jobs': -1,\n"
        "    }\n"
        "\n"
        "    # XGBoost params\n"
        "    xgb_params = {\n"
        "        'objective': 'reg:squarederror',\n"
        "        'eval_metric': 'mae',\n"
        "        'max_depth': 6,\n"
        "        'learning_rate': 0.05,\n"
        "        'n_estimators': 200,\n"
        "        'subsample': 0.8,\n"
        "        'colsample_bytree': 0.8,\n"
        "        'random_state': 42,\n"
        "        'verbosity': 0,\n"
        "        'n_jobs': -1,\n"
        "    }\n"
        "\n"
        "    # --- CV Folds ---\n"
        "    for fold_i, (train_idx, val_idx) in enumerate(folds):\n"
        "        X_tr = df.loc[train_idx, feature_cols].values\n"
        "        y_tr = df.loc[train_idx, TARGET].values\n"
        "        X_va = df.loc[val_idx, feature_cols].values\n"
        "        y_va = df.loc[val_idx, TARGET].values\n"
        "\n"
        "        # LightGBM\n"
        "        lgb_model = lgb.LGBMRegressor(**lgb_params)\n"
        "        lgb_model.fit(X_tr, y_tr)\n"
        "        lgb_pred = np.clip(lgb_model.predict(X_va), 0, None)\n"
        "        r = evaluate(y_va, lgb_pred, f'{label_prefix}LightGBM')\n"
        "        r['fold'] = fold_i + 1\n"
        "        results.append(r)\n"
        "\n"
        "        # XGBoost\n"
        "        xgb_model = xgb.XGBRegressor(**xgb_params)\n"
        "        xgb_model.fit(X_tr, y_tr)\n"
        "        xgb_pred = np.clip(xgb_model.predict(X_va), 0, None)\n"
        "        r = evaluate(y_va, xgb_pred, f'{label_prefix}XGBoost')\n"
        "        r['fold'] = fold_i + 1\n"
        "        results.append(r)\n"
        "\n"
        "    # --- Final Test ---\n"
        "    train_all_idx = df.index.difference(test_idx)\n"
        "    X_train_all = df.loc[train_all_idx, feature_cols].values\n"
        "    y_train_all = df.loc[train_all_idx, TARGET].values\n"
        "    X_test = df.loc[test_idx, feature_cols].values\n"
        "    y_test = df.loc[test_idx, TARGET].values\n"
        "\n"
        "    # LightGBM final\n"
        "    lgb_model_final = lgb.LGBMRegressor(**lgb_params)\n"
        "    lgb_model_final.fit(X_train_all, y_train_all)\n"
        "    lgb_test_pred = np.clip(lgb_model_final.predict(X_test), 0, None)\n"
        "    r = evaluate(y_test, lgb_test_pred, f'{label_prefix}LightGBM')\n"
        "    r['fold'] = 'Test'\n"
        "    results.append(r)\n"
        "    test_preds['LightGBM'] = lgb_test_pred\n"
        "\n"
        "    # XGBoost final\n"
        "    xgb_model_final = xgb.XGBRegressor(**xgb_params)\n"
        "    xgb_model_final.fit(X_train_all, y_train_all)\n"
        "    xgb_test_pred = np.clip(xgb_model_final.predict(X_test), 0, None)\n"
        "    r = evaluate(y_test, xgb_test_pred, f'{label_prefix}XGBoost')\n"
        "    r['fold'] = 'Test'\n"
        "    results.append(r)\n"
        "    test_preds['XGBoost'] = xgb_test_pred\n"
        "\n"
        "    return results, lgb_model_final, xgb_model_final, test_preds\n"
        "\n"
        "\n"
        "print('Function run_ml_models() defined.')"
    )

    code(
        "# ══════════════════════════════════════════════════════════════\n"
        "# CATEGORY LEVEL — ML Models\n"
        "# ══════════════════════════════════════════════════════════════\n"
        "\n"
        "# Encode category\n"
        "cat_enc, cat_mappings = encode_categoricals(cat_features, ['category'])\n"
        "cat_all_features = NUMERIC_FEATURES + ['category_enc']\n"
        "\n"
        "cat_ml_results, cat_lgb_model, cat_xgb_model, cat_test_preds = run_ml_models(\n"
        "    cat_enc, cat_all_features, ['category_enc'],\n"
        "    cat_folds, cat_test_idx, label_prefix=''\n"
        ")\n"
        "\n"
        "cat_ml_df = pd.DataFrame(cat_ml_results)\n"
        "\n"
        "print('=== Category Level — ML Results (CV mean ± std) ===')\n"
        "cv_ml = (\n"
        "    cat_ml_df[cat_ml_df['fold'] != 'Test']\n"
        "    .groupby('model')[['MAE', 'RMSE', 'SMAPE']]\n"
        "    .agg(['mean', 'std'])\n"
        ")\n"
        "print(cv_ml.round(2))\n"
        "print()\n"
        "print('=== Category Level — ML Results (Final Test) ===')\n"
        "print(cat_ml_df[cat_ml_df['fold'] == 'Test'][['model', 'MAE', 'RMSE', 'SMAPE']]\n"
        "      .to_string(index=False))"
    )

    code(
        "# ══════════════════════════════════════════════════════════════\n"
        "# CATEGORY × COUNTRY LEVEL — ML Models\n"
        "# ══════════════════════════════════════════════════════════════\n"
        "\n"
        "# Encode category + country\n"
        "catco_enc, catco_mappings = encode_categoricals(\n"
        "    catco_features, ['category', 'country']\n"
        ")\n"
        "catco_all_features = NUMERIC_FEATURES + ['category_enc', 'country_enc']\n"
        "\n"
        "catco_ml_results, catco_lgb_model, catco_xgb_model, catco_test_preds = run_ml_models(\n"
        "    catco_enc, catco_all_features, ['category_enc', 'country_enc'],\n"
        "    catco_folds, catco_test_idx, label_prefix=''\n"
        ")\n"
        "\n"
        "catco_ml_df = pd.DataFrame(catco_ml_results)\n"
        "\n"
        "print('=== Category×Country Level — ML Results (CV mean ± std) ===')\n"
        "cv_catco = (\n"
        "    catco_ml_df[catco_ml_df['fold'] != 'Test']\n"
        "    .groupby('model')[['MAE', 'RMSE', 'SMAPE']]\n"
        "    .agg(['mean', 'std'])\n"
        ")\n"
        "print(cv_catco.round(2))\n"
        "print()\n"
        "print('=== Category×Country Level — ML Results (Final Test) ===')\n"
        "print(catco_ml_df[catco_ml_df['fold'] == 'Test'][['model', 'MAE', 'RMSE', 'SMAPE']]\n"
        "      .to_string(index=False))"
    )

    code(
        "# ── Chạy baselines cho Category×Country level ──\n"
        "catco_baseline_results = run_baselines(\n"
        "    catco_enc, catco_all_features, catco_folds, catco_test_idx, label_prefix=''\n"
        ")\n"
        "catco_baseline_df = pd.DataFrame(catco_baseline_results)\n"
        "\n"
        "print('=== Category×Country Level — Baseline Results (Final Test) ===')\n"
        "print(catco_baseline_df[catco_baseline_df['fold'] == 'Test']\n"
        "      [['model', 'MAE', 'RMSE', 'SMAPE']].to_string(index=False))"
    )

    # ── 12. MODEL COMPARISON ──────────────────────────────────────────────
    md(
        "## 12. So sánh mô hình\n"
        "\n"
        "Bảng tổng hợp tất cả models × cả 2 granularity. "
        "Báo cáo **CV mean ± std** để đánh giá ổn định, và **Final Test** để đánh giá production."
    )

    code(
        "# ── Tổng hợp tất cả kết quả ──\n"
        "\n"
        "def summarize_results(baseline_df, ml_df, granularity_label):\n"
        '    """Tạo bảng tổng hợp CV + Test cho 1 granularity."""\n'
        "    all_df = pd.concat([baseline_df, ml_df], ignore_index=True)\n"
        "\n"
        "    # CV summary (mean ± std)\n"
        "    cv = all_df[all_df['fold'] != 'Test'].groupby('model').agg(\n"
        "        MAE_mean=('MAE', 'mean'), MAE_std=('MAE', 'std'),\n"
        "        RMSE_mean=('RMSE', 'mean'), RMSE_std=('RMSE', 'std'),\n"
        "        SMAPE_mean=('SMAPE', 'mean'), SMAPE_std=('SMAPE', 'std'),\n"
        "    ).reset_index()\n"
        "    cv['CV_MAE'] = cv.apply(lambda r: f\"{r['MAE_mean']:.2f} ± {r['MAE_std']:.2f}\", axis=1)\n"
        "    cv['CV_RMSE'] = cv.apply(lambda r: f\"{r['RMSE_mean']:.2f} ± {r['RMSE_std']:.2f}\", axis=1)\n"
        "    cv['CV_SMAPE'] = cv.apply(lambda r: f\"{r['SMAPE_mean']:.1f}% ± {r['SMAPE_std']:.1f}%\", axis=1)\n"
        "\n"
        "    # Test\n"
        "    test = all_df[all_df['fold'] == 'Test'][['model', 'MAE', 'RMSE', 'SMAPE']].copy()\n"
        "    test.columns = ['model', 'Test_MAE', 'Test_RMSE', 'Test_SMAPE']\n"
        "\n"
        "    summary = cv[['model', 'CV_MAE', 'CV_RMSE', 'CV_SMAPE']].merge(test, on='model', how='left')\n"
        "    summary['Granularity'] = granularity_label\n"
        "\n"
        "    # Sort by Test MAE\n"
        "    summary = summary.sort_values('Test_MAE')\n"
        "    return summary\n"
        "\n"
        "\n"
        "cat_summary = summarize_results(cat_baseline_df, cat_ml_df, 'Category')\n"
        "catco_summary = summarize_results(catco_baseline_df, catco_ml_df, 'Cat×Country')\n"
        "\n"
        "full_comparison = pd.concat([cat_summary, catco_summary], ignore_index=True)\n"
        "\n"
        "print('╔══════════════════════════════════════════════════════════════════════════════╗')\n"
        "print('║           BẢNG SO SÁNH TẤT CẢ MÔ HÌNH — DEMAND FORECASTING                ║')\n"
        "print('╚══════════════════════════════════════════════════════════════════════════════╝')\n"
        "print()\n"
        "display_cols = ['Granularity', 'model', 'CV_MAE', 'CV_RMSE', 'CV_SMAPE',\n"
        "                'Test_MAE', 'Test_RMSE', 'Test_SMAPE']\n"
        "print(full_comparison[display_cols].to_string(index=False))"
    )

    code(
        "# ── Biểu đồ so sánh MAE trên Test set ──\n"
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
        "\n"
        "for ax, (label, summary) in zip(axes, [('Category', cat_summary), ('Cat×Country', catco_summary)]):\n"
        "    colors = ['#4CAF50' if 'LightGBM' in m else '#2196F3' if 'XGBoost' in m\n"
        "              else '#FF9800' if 'LinReg' in m else '#9E9E9E'\n"
        "              for m in summary['model']]\n"
        "    bars = ax.barh(summary['model'], summary['Test_MAE'], color=colors, edgecolor='white')\n"
        "    ax.set_xlabel('MAE (lower is better)', fontsize=11)\n"
        "    ax.set_title(f'{label} Level — Test MAE', fontsize=13, fontweight='bold')\n"
        "    for bar, val in zip(bars, summary['Test_MAE']):\n"
        "        ax.text(val + 0.1, bar.get_y() + bar.get_height()/2,\n"
        "                f'{val:.2f}', va='center', fontsize=10)\n"
        "    ax.invert_yaxis()\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "# Xác định best model\n"
        "best_cat = cat_summary.iloc[0]\n"
        "best_catco = catco_summary.iloc[0]\n"
        "print(f'\\nBest Category-level model: {best_cat[\"model\"]} (Test MAE = {best_cat[\"Test_MAE\"]:.2f})')\n"
        "print(f'Best Cat×Country model: {best_catco[\"model\"]} (Test MAE = {best_catco[\"Test_MAE\"]:.2f})')"
    )

    # ── 13. FEATURE IMPORTANCE ────────────────────────────────────────────
    md(
        "## 13. Feature Importance\n"
        "\n"
        "Phân tích feature importance từ LightGBM — model chính. "
        "Giúp hiểu yếu tố nào ảnh hưởng nhất tới demand."
    )

    code(
        "def plot_feature_importance(model, feature_names, title, top_n=15):\n"
        '    """Vẽ biểu đồ feature importance."""\n'
        "    importance = model.feature_importances_\n"
        "    fi_df = pd.DataFrame({\n"
        "        'feature': feature_names,\n"
        "        'importance': importance\n"
        "    }).sort_values('importance', ascending=True).tail(top_n)\n"
        "\n"
        "    fig, ax = plt.subplots(figsize=(10, 6))\n"
        "    ax.barh(fi_df['feature'], fi_df['importance'], color='#4CAF50', edgecolor='white')\n"
        "    ax.set_xlabel('Importance (split count)', fontsize=11)\n"
        "    ax.set_title(title, fontsize=13, fontweight='bold')\n"
        "    plt.tight_layout()\n"
        "    plt.show()\n"
        "    return fi_df\n"
        "\n"
        "\n"
        "# ── Category Level ──\n"
        "print('=== Feature Importance: Category Level (LightGBM) ===')\n"
        "cat_fi = plot_feature_importance(\n"
        "    cat_lgb_model, cat_all_features,\n"
        "    'LightGBM Feature Importance — Category Level'\n"
        ")\n"
        "\n"
        "print('\\nTop 5 features:')\n"
        "for _, row in cat_fi.tail(5).iloc[::-1].iterrows():\n"
        "    print(f'  {row[\"feature\"]:20s}: {row[\"importance\"]:.0f}')"
    )

    code(
        "# ── Category × Country Level ──\n"
        "print('=== Feature Importance: Category×Country Level (LightGBM) ===')\n"
        "catco_fi = plot_feature_importance(\n"
        "    catco_lgb_model, catco_all_features,\n"
        "    'LightGBM Feature Importance — Category×Country Level'\n"
        ")\n"
        "\n"
        "print('\\nTop 5 features:')\n"
        "for _, row in catco_fi.tail(5).iloc[::-1].iterrows():\n"
        "    print(f'  {row[\"feature\"]:20s}: {row[\"importance\"]:.0f}')"
    )

    md(
        "### Giải thích Feature Importance\n"
        "\n"
        "| Feature | Ý nghĩa khi quan trọng |\n"
        "|---|---|\n"
        "| `lag_1` | Demand hôm qua có tương quan cao với hôm nay (momentum) |\n"
        "| `lag_7` | Weekly pattern rõ ràng — cùng ngày tuần trước dự báo tốt |\n"
        "| `rolling_mean_7` | Xu hướng trung bình gần đây phản ánh mức demand |\n"
        "| `day_of_week` | Ngày trong tuần ảnh hưởng hành vi mua sắm |\n"
        "| `category_enc` | Các category có demand level khác nhau |\n"
        "| `country_enc` | Các quốc gia có mức demand khác nhau (France > Portugal) |\n"
        "| `has_discount` | Khuyến mãi có thể thúc đẩy demand |"
    )

    # ── 14. 7-DAY FORECAST ────────────────────────────────────────────────
    md(
        "## 14. Dự báo 7 ngày — Thực tế vs Dự báo\n"
        "\n"
        "Hiển thị giá trị thực vs dự báo cho 7 ngày cuối cùng (test set).\n"
        "\n"
        "> **Lưu ý**: Đây là đánh giá one-step-ahead — mỗi ngày sử dụng giá trị thực "
        "của ngày trước đó (walk-forward). Trong production, cần recursive prediction "
        "cho multi-step forecast."
    )

    code(
        "# ══════════════════════════════════════════════════════════════\n"
        "# CATEGORY LEVEL — 7-day forecast visualization\n"
        "# ══════════════════════════════════════════════════════════════\n"
        "\n"
        "test_cat = cat_enc.loc[cat_test_idx].copy()\n"
        "test_cat['lgb_pred'] = cat_test_preds['LightGBM']\n"
        "test_cat['xgb_pred'] = cat_test_preds['XGBoost']\n"
        "\n"
        "# Lấy thêm 14 ngày training cuối để vẽ context\n"
        "train_all = cat_enc.index.difference(cat_test_idx)\n"
        "last_train_date = cat_enc.loc[train_all, 'full_date'].max()\n"
        "context_start = last_train_date - pd.Timedelta(days=13)\n"
        "context_mask = (cat_enc['full_date'] >= context_start) & (cat_enc['full_date'] <= last_train_date)\n"
        "context = cat_enc.loc[context_mask]\n"
        "\n"
        "fig, axes = plt.subplots(3, 2, figsize=(16, 12))\n"
        "axes = axes.flatten()\n"
        "\n"
        "for i, cat in enumerate(all_categories):\n"
        "    ax = axes[i]\n"
        "    ctx = context[context['category'] == cat]\n"
        "    tst = test_cat[test_cat['category'] == cat]\n"
        "\n"
        "    # Context (train)\n"
        "    ax.plot(ctx['full_date'], ctx['daily_quantity'],\n"
        "            'o-', color='#9E9E9E', linewidth=1.5, markersize=4, label='Train (context)')\n"
        "    # Actual test\n"
        "    ax.plot(tst['full_date'], tst['daily_quantity'],\n"
        "            'o-', color='#2196F3', linewidth=2, markersize=6, label='Actual')\n"
        "    # LightGBM prediction\n"
        "    ax.plot(tst['full_date'], tst['lgb_pred'],\n"
        "            's--', color='#4CAF50', linewidth=2, markersize=6, label='LightGBM')\n"
        "    # XGBoost prediction\n"
        "    ax.plot(tst['full_date'], tst['xgb_pred'],\n"
        "            '^:', color='#FF9800', linewidth=1.5, markersize=5, label='XGBoost')\n"
        "\n"
        "    ax.axvline(x=last_train_date, color='red', linestyle='--', alpha=0.5, label='Train/Test cutoff')\n"
        "    ax.set_title(f'{cat}', fontsize=12, fontweight='bold')\n"
        "    ax.set_ylabel('Quantity')\n"
        "    ax.grid(True, alpha=0.3)\n"
        "    if i == 0:\n"
        "        ax.legend(fontsize=8, loc='upper left')\n"
        "\n"
        "# Hide extra subplot\n"
        "if len(all_categories) < len(axes):\n"
        "    axes[-1].set_visible(False)\n"
        "\n"
        "fig.suptitle('Category Level — Actual vs Forecast (7 ngày cuối)',\n"
        "             fontsize=15, fontweight='bold', y=1.01)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    code(
        "# ══════════════════════════════════════════════════════════════\n"
        "# CATEGORY × COUNTRY — 7-day forecast (aggregate view)\n"
        "# ══════════════════════════════════════════════════════════════\n"
        "\n"
        "test_catco = catco_enc.loc[catco_test_idx].copy()\n"
        "test_catco['lgb_pred'] = catco_test_preds['LightGBM']\n"
        "\n"
        "# Tổng theo Country\n"
        "country_agg_actual = test_catco.groupby('country')['daily_quantity'].sum()\n"
        "country_agg_pred = test_catco.groupby('country')['lgb_pred'].sum()\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "x = np.arange(len(country_agg_actual))\n"
        "width = 0.35\n"
        "ax.bar(x - width/2, country_agg_actual.values, width, label='Actual', color='#2196F3', edgecolor='white')\n"
        "ax.bar(x + width/2, country_agg_pred.values, width, label='LightGBM Forecast', color='#4CAF50', edgecolor='white')\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels(country_agg_actual.index, rotation=30)\n"
        "ax.set_ylabel('Total Quantity (7 ngày)', fontsize=11)\n"
        "ax.set_title('Cat×Country Level — Tổng Quantity: Actual vs Forecast theo Country',\n"
        "             fontsize=13, fontweight='bold')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "# Tổng theo Category\n"
        "cat_agg_actual = test_catco.groupby('category')['daily_quantity'].sum()\n"
        "cat_agg_pred = test_catco.groupby('category')['lgb_pred'].sum()\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "x = np.arange(len(cat_agg_actual))\n"
        "ax.bar(x - width/2, cat_agg_actual.values, width, label='Actual', color='#2196F3', edgecolor='white')\n"
        "ax.bar(x + width/2, cat_agg_pred.values, width, label='LightGBM Forecast', color='#4CAF50', edgecolor='white')\n"
        "ax.set_xticks(x)\n"
        "ax.set_xticklabels(cat_agg_actual.index, rotation=30)\n"
        "ax.set_ylabel('Total Quantity (7 ngày)', fontsize=11)\n"
        "ax.set_title('Cat×Country Level — Tổng Quantity: Actual vs Forecast theo Category',\n"
        "             fontsize=13, fontweight='bold')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()"
    )

    code(
        "# ── Chi tiết sai số theo từng ngày test (Category level) ──\n"
        "daily_error = test_cat.groupby('full_date').apply(\n"
        "    lambda g: pd.Series({\n"
        "        'actual': g['daily_quantity'].sum(),\n"
        "        'lgb_pred': g['lgb_pred'].sum(),\n"
        "        'error': (g['daily_quantity'] - g['lgb_pred']).abs().sum(),\n"
        "    })\n"
        ").reset_index()\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(12, 4))\n"
        "ax.plot(daily_error['full_date'], daily_error['actual'],\n"
        "        'o-', color='#2196F3', linewidth=2, markersize=8, label='Actual Total')\n"
        "ax.plot(daily_error['full_date'], daily_error['lgb_pred'],\n"
        "        's--', color='#4CAF50', linewidth=2, markersize=8, label='LightGBM Total')\n"
        "ax.fill_between(daily_error['full_date'],\n"
        "                daily_error['actual'], daily_error['lgb_pred'],\n"
        "                alpha=0.2, color='#FF5722', label='Error')\n"
        "ax.set_title('Daily Total Quantity — Actual vs LightGBM (7 ngày test)',\n"
        "             fontsize=13, fontweight='bold')\n"
        "ax.set_ylabel('Total Quantity')\n"
        "ax.legend()\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Chi tiết sai số từng ngày:')\n"
        "daily_error['pct_error'] = (\n"
        "    (daily_error['actual'] - daily_error['lgb_pred']).abs()\n"
        "    / daily_error['actual'].replace(0, np.nan) * 100\n"
        ")\n"
        "print(daily_error[['full_date', 'actual', 'lgb_pred', 'error', 'pct_error']].to_string(index=False))"
    )

    # ── 15. CONCLUSION ────────────────────────────────────────────────────
    md(
        "## 15. Kết luận\n"
        "\n"
        "### Mô hình tốt nhất\n"
        "Dựa trên kết quả thực nghiệm, **LightGBM** là mô hình phù hợp nhất cho bài toán "
        "Demand Forecasting với dataset này. Kết quả cụ thể:\n"
        "\n"
        "| Granularity | Model | Test MAE | Test RMSE | Test SMAPE |\n"
        "|---|---|---|---|---|\n"
        "| Category | LightGBM | *(xem bảng ở mục 12)* | | |\n"
        "| Cat×Country | LightGBM | *(xem bảng ở mục 12)* | | |\n"
        "\n"
        "### Ưu điểm của LightGBM cho bài toán này\n"
        "1. **Xử lý tốt dataset nhỏ** — không overfit như Deep Learning\n"
        "2. **Native categorical support** — category, country không cần one-hot encoding phức tạp\n"
        "3. **Feature importance rõ ràng** — giúp business hiểu yếu tố nào ảnh hưởng demand\n"
        "4. **Tốc độ nhanh** — train + predict trong vài giây\n"
        "\n"
        "### Hạn chế\n"
        "1. **Dữ liệu chỉ có 51 ngày** — chưa đủ để phát hiện seasonal patterns dài hạn (cần ≥ 2 năm)\n"
        "2. **Chỉ 1 brand (Tiva)** — không thể phân tích demand theo brand\n"
        "3. **SKU-level forecast không khả thi** — trung bình chỉ 4.3 data points/sản phẩm\n"
        "4. **Evaluation dạng walk-forward (one-step-ahead)** — trong production cần recursive "
        "prediction cho multi-step forecast\n"
        "\n"
        "### Vì sao KHÔNG dùng SARIMA/Prophet/Deep Learning?\n"
        "- **SARIMA**: Cần ≥ 2 seasonal cycles (≥ 2 năm cho yearly seasonality). Chỉ có 51 ngày → KHÔNG ĐỦ.\n"
        "- **Prophet**: Thiết kế cho dữ liệu ≥ 1 năm. 51 ngày cho kết quả không đáng tin cậy.\n"
        "- **LSTM/GRU/TFT**: Cần hàng nghìn data points để tránh overfit. 51 ngày × 5 categories = "
        "255 mẫu → HOÀN TOÀN KHÔNG ĐỦ.\n"
        "\n"
        "### Hướng cải thiện khi có thêm dữ liệu\n"
        "1. **Khi có ≥ 6 tháng**: Thử Prophet để auto-detect weekly/monthly seasonality\n"
        "2. **Khi có ≥ 1 năm**: SARIMA trở nên khả thi; có thể capture yearly seasonality\n"
        "3. **Khi có ≥ 2 năm**: Deep Learning (LSTM, TFT) bắt đầu có ý nghĩa\n"
        "4. **Khi có nhiều sản phẩm hơn mỗi ngày**: SKU-level forecast trở nên khả thi\n"
        "5. **External features**: thêm dữ liệu thời tiết, sự kiện, holiday → cải thiện accuracy\n"
        "6. **Real-time pipeline**: tích hợp Airflow/Prefect để chạy forecasting tự động hàng tuần"
    )

    # ── Write notebook ────────────────────────────────────────────────────
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    output_path = NOTEBOOK_DIR / "05_demand_forecasting.ipynb"
    output_path.write_text(json.dumps(nb, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Notebook written to {output_path}")
    print(f"Total cells: {len(cells)} (markdown: {sum(1 for c in cells if c['cell_type'] == 'markdown')}, code: {sum(1 for c in cells if c['cell_type'] == 'code')})")


if __name__ == "__main__":
    main()
